name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
  #push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]

permissions:
  contents: write

jobs:
  export-from-dev:
    runs-on: windows-latest
    #env:
      #RUNNER_DEBUG: 1
    
    environment: Dev

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{ secrets.URL }}
        app-id: ${{ secrets.CLIENTID }}
        client-secret: ${{ secrets.SECRET }}
        tenant-id: ${{ secrets.TENANTID }}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ secrets.URL }}
        app-id: ${{ secrets.CLIENTID }}
        client-secret: ${{ secrets.SECRET }}
        tenant-id: ${{ secrets.TENANTID }}
        solution-name: Solution1
        solution-output-file: out/exported/Solution1.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/Solution1.zip
        solution-folder: out/solutions/Solution1
        solution-type: Both
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/Solution1
        solution-target-folder: solutions/Solution1
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true



